; ============================================================================
; Little Tree Wallpaper Next - NSIS installer (Modern UI 2, multilingual)
;
; Languages : Simplified Chinese / English / Traditional Chinese / Japanese
; Branding  : header + welcome bitmaps and icon are generated by tools/build.py
; Versioning: APP_VERSION (display) / FILE_VERSION (numeric X.X.X.X for
;             VIProductVersion) / BUILD_CHANNEL / SOURCE_DIR / OUT_FILE /
;             ASSETS_DIR are injected via makensis /D defines; do not hardcode
;             them here.
; ============================================================================

Unicode true
ManifestDPIAware true
SetCompressor /SOLID lzma
SetCompressorDictSize 64

!ifndef APP_VERSION
  !define APP_VERSION "2.0.0"
!endif
; VIProductVersion requires a strictly numeric X.X.X.X value and rejects
; prerelease suffixes. tools/build.py always injects FILE_VERSION derived from
; APP_VERSION (prerelease dropped, zero-padded to four segments). This fallback
; keeps plain numeric versions working when compiling setup.nsi directly.
!ifndef FILE_VERSION
  !define FILE_VERSION "${APP_VERSION}.0"
!endif
!ifndef BUILD_CHANNEL
  !define BUILD_CHANNEL "beta"
!endif
!ifndef SOURCE_DIR
  !error "SOURCE_DIR must point at the PyInstaller onedir bundle"
!endif
!ifndef ASSETS_DIR
  !error "ASSETS_DIR must point at the generated installer assets"
!endif
!ifndef LICENSE_FILE
  !define LICENSE_FILE "..\LICENSES"
!endif
!ifndef OUT_FILE
  !define OUT_FILE "LittleTreeWallpaper-Setup.exe"
!endif
!ifndef OUT_NAME
  !define OUT_NAME "LittleTreeWallpaper-Setup.exe"
!endif

!define PRODUCT_ID            "LittleTreeWallpaper"
!define PRODUCT_EXE           "LittleTreeWallpaper.exe"
!define PRODUCT_UNINSTALL_EXE "Uninstall.exe"
!define PRODUCT_PUBLISHER     "LittleTreeStudio"
!define PRODUCT_WEBSITE       "https://github.com/Little-Tree-Studio/Little-Tree-Wallpaper-Next"
!define PRODUCT_REG_KEY       "Software\LittleTreeStudio\LittleTreeWallpaper"
!define PRODUCT_UNINST_KEY    "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_ID}"

Name "$(LTW_NAME)"
OutFile "${OUT_FILE}"
InstallDir "$PROGRAMFILES64\${PRODUCT_ID}"
InstallDirRegKey HKLM "${PRODUCT_REG_KEY}" "InstallDir"
RequestExecutionLevel admin
ShowInstDetails show
ShowUnInstDetails show
AllowSkipFiles off
BrandingText "Little Tree Wallpaper Next"

VIProductVersion "${FILE_VERSION}"
VIAddVersionKey "ProductName"      "Little Tree Wallpaper Next"
VIAddVersionKey "CompanyName"      "${PRODUCT_PUBLISHER}"
VIAddVersionKey "FileVersion"      "${FILE_VERSION}"
VIAddVersionKey "ProductVersion"   "${APP_VERSION}"
VIAddVersionKey "FileDescription"  "Little Tree Wallpaper Next Setup"
VIAddVersionKey "LegalCopyright"   "GNU Affero General Public License v3.0"
VIAddVersionKey "OriginalFilename" "${OUT_NAME}"

!include "MUI2.nsh"
!include "FileFunc.nsh"
!include "LogicLib.nsh"
!include "x64.nsh"

; ------------------------------ UI appearance ------------------------------
!define MUI_ABORTWARNING
!define MUI_ICON   "${ASSETS_DIR}\logo.ico"
!define MUI_UNICON "${ASSETS_DIR}\logo.ico"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_RIGHT
!define MUI_HEADERIMAGE_BITMAP "${ASSETS_DIR}\header.bmp"
!define MUI_WELCOMEFINISHPAGE_BITMAP   "${ASSETS_DIR}\welcome.bmp"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "${ASSETS_DIR}\welcome.bmp"
!define MUI_WELCOMEPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_EXE}"
!define MUI_FINISHPAGE_RUN_TEXT "$(LTW_FINISH_RUN)"
!define MUI_FINISHPAGE_LINK "$(LTW_FINISH_LINK)"
!define MUI_FINISHPAGE_LINK_LOCATION "${PRODUCT_WEBSITE}"
!define MUI_LANGDLL_REGISTRY_ROOT "HKLM"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_REG_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "InstallerLanguage"

; --------------------- Per-language UI font optimization ---------------------
; The stock dialog font (MS Shell Dlg -> SimSun for Chinese) renders poorly.
; Instead, every control's font is cloned at runtime with a modern face
; (Microsoft YaHei / Segoe UI / Microsoft JhengHei / Yu Gothic UI) while
; keeping the original size and weight, so dialog layouts stay intact.
!define MUI_CUSTOMFUNCTION_GUIINIT   "InitInstallerFont"
!define MUI_CUSTOMFUNCTION_UNGUIINIT "un.InitInstallerFont"

Var FontDPI
Var UpdatePid
Var LaunchAfterUpdate

!macro LTW_FONT_FUNCTIONS un
  Function ${un}ApplyFontToChildren
    ; $R9 = parent window whose direct children receive the new font face
    Push $R0
    Push $R4
    Push $R5
    Push $R6
    Push $R7
    Push $R8
    System::Call "user32::GetWindow(p $R9, i 5) p.s" ; GW_CHILD
    Pop $R8
    ${While} $R8 <> 0
      SendMessage $R8 ${WM_GETFONT} 0 0 $R7
      ${If} $R7 <> 0
        System::Call "gdi32::GetObjectW(p $R7, i 92, @R6)"
        System::Call "*$R6(i.R0, i, i, i, i.R5)" ; lfHeight (px), lfWeight
        ; The CreateFont instruction takes POINTS, not pixels: it applies
        ; -MulDiv(pt, GetDeviceCaps(LOGPIXELSY), 72) internally. Feed it the
        ; pixel height converted back to points or fonts get scaled twice.
        ${If} $R0 < 0
          IntOp $R0 $R0 * -1
        ${EndIf}
        IntOp $R0 $R0 * 72
        IntOp $R0 $R0 / $FontDPI
        ${If} $R0 < 1
          StrCpy $R0 1
        ${EndIf}
        CreateFont $R4 "$(LTW_FONT_FACE)" $R0 $R5
        SendMessage $R8 ${WM_SETFONT} $R4 1
      ${EndIf}
      System::Call "user32::GetWindow(p $R8, i 2) p.s" ; GW_HWNDNEXT
      Pop $R8
    ${EndWhile}
    Pop $R8
    Pop $R7
    Pop $R6
    Pop $R5
    Pop $R4
    Pop $R0
  FunctionEnd

  Function ${un}ApplyFontsDeep
    ; Restyle the outer dialog plus every embedded page dialog. Both classic
    ; MUI pages and nsDialogs pages (welcome/finish) live somewhere inside the
    ; child tree of $HWNDPARENT, and a previous page's dialog may still exist
    ; during a transition, so every level is swept instead of FindWindow.
    Push $R8
    System::Call "user32::GetDC(p $HWNDPARENT) p.s"
    Pop $R8
    System::Call "gdi32::GetDeviceCaps(p $R8, i 90) i.s" ; LOGPIXELSY
    Pop $FontDPI
    System::Call "user32::ReleaseDC(p $HWNDPARENT, p $R8)"
    ${If} $FontDPI < 96
      StrCpy $FontDPI 96
    ${EndIf}
    StrCpy $R9 $HWNDPARENT
    Call ${un}ApplyFontToChildren
    System::Call "user32::GetWindow(p $HWNDPARENT, i 5) p.s" ; GW_CHILD
    Pop $R8
    ${While} $R8 <> 0
      StrCpy $R9 $R8
      Call ${un}ApplyFontToChildren
      System::Call "user32::GetWindow(p $R8, i 2) p.s" ; GW_HWNDNEXT
      Pop $R8
    ${EndWhile}
    Pop $R8
  FunctionEnd

  Function ${un}InitInstallerFont
    Call ${un}ApplyFontsDeep
  FunctionEnd

  Function ${un}PageFontShow
    Call ${un}ApplyFontsDeep
  FunctionEnd
!macroend
!insertmacro LTW_FONT_FUNCTIONS ""
!insertmacro LTW_FONT_FUNCTIONS "un."

; --------------------------------- Pages -----------------------------------
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "PageFontShow"
!insertmacro MUI_PAGE_WELCOME
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "PageFontShow"
!insertmacro MUI_PAGE_LICENSE "${LICENSE_FILE}"
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "PageFontShow"
!insertmacro MUI_PAGE_COMPONENTS
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "PageFontShow"
!insertmacro MUI_PAGE_DIRECTORY
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "PageFontShow"
!insertmacro MUI_PAGE_INSTFILES
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "PageFontShow"
!insertmacro MUI_PAGE_FINISH

!define MUI_PAGE_CUSTOMFUNCTION_SHOW "un.PageFontShow"
!insertmacro MUI_UNPAGE_CONFIRM
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "un.PageFontShow"
!insertmacro MUI_UNPAGE_INSTFILES
!define MUI_PAGE_CUSTOMFUNCTION_SHOW "un.PageFontShow"
!insertmacro MUI_UNPAGE_FINISH

; ------------------------------- Languages ---------------------------------
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "Japanese"

; ---------------------------- Localized strings ----------------------------
LangString LTW_NAME ${LANG_SIMPCHINESE} "小树壁纸 Next"
LangString LTW_NAME ${LANG_ENGLISH}     "Little Tree Wallpaper Next"
LangString LTW_NAME ${LANG_TRADCHINESE} "小樹桌布 Next"
LangString LTW_NAME ${LANG_JAPANESE}    "Little Tree Wallpaper Next"

LangString LTW_FONT_FACE ${LANG_SIMPCHINESE} "Microsoft YaHei"
LangString LTW_FONT_FACE ${LANG_ENGLISH}     "Segoe UI"
LangString LTW_FONT_FACE ${LANG_TRADCHINESE} "Microsoft JhengHei"
LangString LTW_FONT_FACE ${LANG_JAPANESE}    "Yu Gothic UI"

LangString LTW_SEC_MAIN ${LANG_SIMPCHINESE} "小树壁纸 Next（必需）"
LangString LTW_SEC_MAIN ${LANG_ENGLISH}     "Little Tree Wallpaper Next (required)"
LangString LTW_SEC_MAIN ${LANG_TRADCHINESE} "小樹桌布 Next（必要）"
LangString LTW_SEC_MAIN ${LANG_JAPANESE}    "Little Tree Wallpaper Next（必須）"

LangString LTW_SEC_MAIN_DESC ${LANG_SIMPCHINESE} "安装主程序及全部运行组件。"
LangString LTW_SEC_MAIN_DESC ${LANG_ENGLISH}     "Installs the main application and all runtime components."
LangString LTW_SEC_MAIN_DESC ${LANG_TRADCHINESE} "安裝主程式及所有執行元件。"
LangString LTW_SEC_MAIN_DESC ${LANG_JAPANESE}    "メインプログラムとすべてのランタイムコンポーネントをインストールします。"

LangString LTW_SEC_DESKTOP ${LANG_SIMPCHINESE} "桌面快捷方式"
LangString LTW_SEC_DESKTOP ${LANG_ENGLISH}     "Desktop shortcut"
LangString LTW_SEC_DESKTOP ${LANG_TRADCHINESE} "桌面捷徑"
LangString LTW_SEC_DESKTOP ${LANG_JAPANESE}    "デスクトップショートカット"

LangString LTW_SEC_DESKTOP_DESC ${LANG_SIMPCHINESE} "在桌面上创建快捷方式。"
LangString LTW_SEC_DESKTOP_DESC ${LANG_ENGLISH}     "Creates a shortcut on the desktop."
LangString LTW_SEC_DESKTOP_DESC ${LANG_TRADCHINESE} "在桌面上建立捷徑。"
LangString LTW_SEC_DESKTOP_DESC ${LANG_JAPANESE}    "デスクトップにショートカットを作成します。"

LangString LTW_UNINSTALL ${LANG_SIMPCHINESE} "卸载小树壁纸 Next"
LangString LTW_UNINSTALL ${LANG_ENGLISH}     "Uninstall Little Tree Wallpaper Next"
LangString LTW_UNINSTALL ${LANG_TRADCHINESE} "解除安裝小樹桌布 Next"
LangString LTW_UNINSTALL ${LANG_JAPANESE}    "Little Tree Wallpaper Next をアンインストール"

LangString LTW_FINISH_RUN ${LANG_SIMPCHINESE} "运行小树壁纸 Next"
LangString LTW_FINISH_RUN ${LANG_ENGLISH}     "Launch Little Tree Wallpaper Next"
LangString LTW_FINISH_RUN ${LANG_TRADCHINESE} "執行小樹桌布 Next"
LangString LTW_FINISH_RUN ${LANG_JAPANESE}    "Little Tree Wallpaper Next を起動"

LangString LTW_FINISH_LINK ${LANG_SIMPCHINESE} "访问项目主页"
LangString LTW_FINISH_LINK ${LANG_ENGLISH}     "Visit project website"
LangString LTW_FINISH_LINK ${LANG_TRADCHINESE} "造訪專案首頁"
LangString LTW_FINISH_LINK ${LANG_JAPANESE}    "プロジェクトサイトを開く"

LangString LTW_ERR_RUNNING ${LANG_SIMPCHINESE} "无法替换正在使用的文件。$\r$\n请先关闭小树壁纸 Next，然后点击“重试”；或点击“取消”中止操作。"
LangString LTW_ERR_RUNNING ${LANG_ENGLISH}     "Some files are currently in use.$\r$\nPlease close Little Tree Wallpaper Next and choose Retry, or Cancel to abort."
LangString LTW_ERR_RUNNING ${LANG_TRADCHINESE} "無法取代使用中的檔案。$\r$\n請先關閉小樹桌布 Next，然後按「重試」；或按「取消」中止操作。"
LangString LTW_ERR_RUNNING ${LANG_JAPANESE}    "使用中のファイルを置き換えられません。$\r$\nLittle Tree Wallpaper Next を終了して「再試行」を押すか、「キャンセル」で中止してください。"

LangString LTW_ERR_X64 ${LANG_SIMPCHINESE} "小树壁纸 Next 需要 64 位 Windows 系统。"
LangString LTW_ERR_X64 ${LANG_ENGLISH}     "Little Tree Wallpaper Next requires 64-bit Windows."
LangString LTW_ERR_X64 ${LANG_TRADCHINESE} "小樹桌布 Next 需要 64 位元 Windows 系統。"
LangString LTW_ERR_X64 ${LANG_JAPANESE}    "Little Tree Wallpaper Next には 64 ビット Windows が必要です。"

; ------------------- Shared "app still running" guard ----------------------
!macro LTW_ENSURE_APP_CLOSED un
  Function ${un}EnsureAppClosed
    ${If} ${FileExists} "$INSTDIR\${PRODUCT_EXE}"
      ${un}close_retry:
        ClearErrors
        Delete "$INSTDIR\${PRODUCT_EXE}"
        ${If} ${Errors}
          IfSilent ${un}silent_abort 0
          MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "$(LTW_ERR_RUNNING)" /SD IDRETRY IDRETRY ${un}close_retry
          Abort
          ${un}silent_abort:
            SetErrorLevel 2
            Abort
        ${EndIf}
    ${EndIf}
  FunctionEnd
!macroend
!insertmacro LTW_ENSURE_APP_CLOSED ""
!insertmacro LTW_ENSURE_APP_CLOSED "un."

; --------------------------------- Init ------------------------------------
Function .onInit
  StrCpy $UpdatePid ""
  StrCpy $LaunchAfterUpdate "0"
  ${GetParameters} $R0
  ClearErrors
  ${GetOptions} $R0 "/UPDATEPID=" $UpdatePid
  ClearErrors
  ${GetOptions} $R0 "/LAUNCH=" $LaunchAfterUpdate
  ${If} $UpdatePid != ""
    System::Call "kernel32::OpenProcess(i 0x00100000, i 0, i $UpdatePid) p.r0"
    ${If} $0 P<> 0
      ; Wait for the running application to release installed files. A finite
      ; timeout prevents an invisible silent updater from hanging forever.
      System::Call "kernel32::WaitForSingleObject(p r0, i 120000) i.r1"
      System::Call "kernel32::CloseHandle(p r0)"
    ${EndIf}
  ${EndIf}
  !insertmacro MUI_LANGDLL_DISPLAY
  ${IfNot} ${RunningX64}
    MessageBox MB_ICONSTOP "$(LTW_ERR_X64)" /SD IDOK
    Abort
  ${EndIf}
FunctionEnd

Function un.onInit
  !insertmacro MUI_UNGETLANGUAGE
FunctionEnd

; -------------------------------- Sections ---------------------------------
Section "$(LTW_SEC_MAIN)" SecMain
  SectionIn RO
  SetOutPath "$INSTDIR"

  Call EnsureAppClosed
  RMDir /r "$INSTDIR"

  File /r "${SOURCE_DIR}\*.*"

  WriteUninstaller "$INSTDIR\${PRODUCT_UNINSTALL_EXE}"

  WriteRegStr HKLM "${PRODUCT_REG_KEY}" "InstallDir" "$INSTDIR"
  WriteRegStr HKLM "${PRODUCT_REG_KEY}" "ShortcutName" "$(LTW_NAME)"
  WriteRegStr HKLM "${PRODUCT_REG_KEY}" "UninstallShortcutName" "$(LTW_UNINSTALL)"

  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "DisplayName"     "$(LTW_NAME)"
  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "DisplayVersion"  "${APP_VERSION}"
  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "Publisher"       "${PRODUCT_PUBLISHER}"
  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "URLInfoAbout"    "${PRODUCT_WEBSITE}"
  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "DisplayIcon"     "$INSTDIR\${PRODUCT_EXE},0"
  WriteRegStr   HKLM "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\${PRODUCT_UNINSTALL_EXE}"
  WriteRegDWORD HKLM "${PRODUCT_UNINST_KEY}" "NoModify"  1
  WriteRegDWORD HKLM "${PRODUCT_UNINST_KEY}" "NoRepair"  1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  WriteRegDWORD HKLM "${PRODUCT_UNINST_KEY}" "EstimatedSize" $0

  CreateDirectory "$SMPROGRAMS\$(LTW_NAME)"
  CreateShortcut  "$SMPROGRAMS\$(LTW_NAME)\$(LTW_NAME).lnk" "$INSTDIR\${PRODUCT_EXE}" "" "$INSTDIR\${PRODUCT_EXE}" 0
  CreateShortcut  "$SMPROGRAMS\$(LTW_NAME)\$(LTW_UNINSTALL).lnk" "$INSTDIR\${PRODUCT_UNINSTALL_EXE}"
SectionEnd

Section "$(LTW_SEC_DESKTOP)" SecDesktop
  CreateShortcut "$DESKTOP\$(LTW_NAME).lnk" "$INSTDIR\${PRODUCT_EXE}" "" "$INSTDIR\${PRODUCT_EXE}" 0
SectionEnd

Function .onInstSuccess
  ${If} $LaunchAfterUpdate == "1"
    Exec '"$INSTDIR\${PRODUCT_EXE}"'
  ${EndIf}
FunctionEnd

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecMain}    "$(LTW_SEC_MAIN_DESC)"
  !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} "$(LTW_SEC_DESKTOP_DESC)"
!insertmacro MUI_FUNCTION_DESCRIPTION_END

; ------------------------------- Uninstall ---------------------------------
Section "Uninstall"
  Call un.EnsureAppClosed

  ReadRegStr $0 HKLM "${PRODUCT_REG_KEY}" "ShortcutName"
  ${If} $0 == ""
    StrCpy $0 "Little Tree Wallpaper Next"
  ${EndIf}
  ReadRegStr $1 HKLM "${PRODUCT_REG_KEY}" "UninstallShortcutName"
  ${If} $1 == ""
    StrCpy $1 "Uninstall Little Tree Wallpaper Next"
  ${EndIf}

  Delete "$DESKTOP\$0.lnk"
  Delete "$SMPROGRAMS\$0\$0.lnk"
  Delete "$SMPROGRAMS\$0\$1.lnk"
  RMDir  "$SMPROGRAMS\$0"

  RMDir /r "$INSTDIR"

  DeleteRegKey HKLM "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_REG_KEY}"
SectionEnd
